### ISSUE TITLE
嗨，代码存在不完整的地方

### ISSUE THREAD

**Issue by rw1995** [Zongyi-Lee/FusionU-Net#1]
能够给出对应的其他网络的训练代码， 方便进行比较呢？

**Comment by Zongyi-Lee** [comment]
很高兴你对这个工作感兴趣！训练模型的代码是通用的，其他不同网络的代码在github也可以很容易找到，为了保持这个项目的简洁我们故意选择了没有将其他各种网络加进来，但同时保留了utils.py中的get_model这个函数，你可以参考我们这个函数的实现，然后根据你的需要训练不同的模型。
